### ISSUE TITLE
Horse Care form - remove large calendar, display main screen when calendar button is clicked

### ISSUE THREAD

**Issue by KthProg** [ITCS2250/HorseFarm#8] opened 2015-05-05 21:36 UTC
Add Horse (drop down)
Also, after switching to the main screen, filter the calendar by horse care.

**Comment by tmadding** [comment] 2015-05-06 04:18
I have no ability to access the database or build it based off the back-up. I cannot build any form of meaningful connections on any off the issues I have been assigned to. Sorry for the inconvenience. I have express 2014 installed but I won't let me edit any part of any databases test ones or otherwise. Any I've spent 2 hours attempting to just download the management tools to no avail. I will try again tomorrow but I hold little faith that I will be able to do anything

**Comment by KthProg** [comment] 2015-05-06 12:17
Don't worry about getting the database connection to work. The UI changes can be done independently and then we'll wire things up afterwards.

**Comment by mgargano4** [comment] 2015-05-06 17:21
what version of visual studio is everyone using? I tried with 2013 in
windows 8.1 and had issues opening it and now in vs 2010 in windows 7 it
says it incompatible. I will try downloading a newer version of visual
studio in windows 7

On Wed, May 6, 2015 at 8:17 AM, KthProg notifications@github.com wrote:

> Don't worry about getting the database connection to work. The UI changes
> can be done independently and then we'll wire things up afterwards.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ITCS2250/HorseFarm/issues/8#issuecomment-99427803.

## 

www.mgargano.com
LinkedIn Profile http://www.linkedin.com/pub/matthew-gargano/7a/306/712/

**Comment by KthProg** [comment] 2015-05-06 17:34
The last time I saved it was in VS 2012 professional in Windows 7, and I think it was originally made in VS 2012. VS 2013 should be fine though. What happens in VS 2013 when you try to open it?

**Comment by mgargano4** [comment] 2015-05-06 17:42
It opens but when I try to open the forms it says there's some errors that need to be fixed before it can be opened. And when I   open it anyways, it's a blank form. I'm currently working on tasks assigned to me, just sketching things out first

-----Original Message-----

**Comment by KthProg** [comment] 2015-05-06 17:51
... Well that is strange... I'll open it up when I get home just to be sure that it isn't broken.

**Comment by mgargano4** [comment] 2015-05-06 18:16
if i get it working before then ill send you an email

On Wed, May 6, 2015 at 1:51 PM, KthProg notifications@github.com wrote:

> ... Well that is strange... I'll open it up when I get home just to be
> sure that it isn't broken.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ITCS2250/HorseFarm/issues/8#issuecomment-99551823.

## 

www.mgargano.com
LinkedIn Profile http://www.linkedin.com/pub/matthew-gargano/7a/306/712/

**Comment by KthProg** [comment] 2015-05-06 18:25
Cool sounds good

**Comment by mgargano4** [comment] 2015-05-07 13:54
i think i figured out what the issue is, I think its because i dont have
the database set up. Im getting this error:
Error 2 The type or namespace name 'HorseFarmDataSet1' does not exist in
the namespace 'HorseFarm' (are you missing an assembly reference?)
 i will attempt to set up the databse and see if i cant get it to work

On Wed, May 6, 2015 at 2:25 PM, KthProg notifications@github.com wrote:

> Cool sounds good
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ITCS2250/HorseFarm/issues/8#issuecomment-99561734.

## 

www.mgargano.com
LinkedIn Profile http://www.linkedin.com/pub/matthew-gargano/7a/306/712/

**Comment by mgargano4** [comment] 2015-05-07 16:57
I got the database set up but now i cant figure out how to connect the
project in vstudio to the database. ill continue to search and play with
it. if you have any tips that would be greatly appreciated. Also i wanna
thank you for volunteering to do all this work, i hope the others are
having more success than i am

On Thu, May 7, 2015 at 9:54 AM, Matthew Gargano mgargano4@gmail.com wrote:

> i think i figured out what the issue is, I think its because i dont have
> the database set up. Im getting this error:
> Error 2 The type or namespace name 'HorseFarmDataSet1' does not exist in
> the namespace 'HorseFarm' (are you missing an assembly reference?)
>  i will attempt to set up the databse and see if i cant get it to work
> 
> On Wed, May 6, 2015 at 2:25 PM, KthProg notifications@github.com wrote:
> 
> > Cool sounds good
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ITCS2250/HorseFarm/issues/8#issuecomment-99561734.
> 
> ## 
> 
> www.mgargano.com
> LinkedIn Profile http://www.linkedin.com/pub/matthew-gargano/7a/306/712/

## 

www.mgargano.com
LinkedIn Profile http://www.linkedin.com/pub/matthew-gargano/7a/306/712/

**Comment by mgargano4** [comment] 2015-05-07 17:21
ok sorry for the million emails, but i got the database connected and all
set up but im still getting several errors. ill send screen shots along
with the email

On Thu, May 7, 2015 at 12:57 PM, Matthew Gargano mgargano4@gmail.com
wrote:

> I got the database set up but now i cant figure out how to connect the
> project in vstudio to the database. ill continue to search and play with
> it. if you have any tips that would be greatly appreciated. Also i wanna
> thank you for volunteering to do all this work, i hope the others are
> having more success than i am
> 
> On Thu, May 7, 2015 at 9:54 AM, Matthew Gargano mgargano4@gmail.com
> wrote:
> 
> > i think i figured out what the issue is, I think its because i dont have
> > the database set up. Im getting this error:
> > Error 2 The type or namespace name 'HorseFarmDataSet1' does not exist in
> > the namespace 'HorseFarm' (are you missing an assembly reference?)
> >  i will attempt to set up the databse and see if i cant get it to work
> > 
> > On Wed, May 6, 2015 at 2:25 PM, KthProg notifications@github.com wrote:
> > 
> > > Cool sounds good
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/ITCS2250/HorseFarm/issues/8#issuecomment-99561734.
> > 
> > ## 
> > 
> > www.mgargano.com
> > LinkedIn Profile
> > http://www.linkedin.com/pub/matthew-gargano/7a/306/712/
> 
> ## 
> 
> www.mgargano.com
> LinkedIn Profile http://www.linkedin.com/pub/matthew-gargano/7a/306/712/

## 

www.mgargano.com
LinkedIn Profile http://www.linkedin.com/pub/matthew-gargano/7a/306/712/

**Comment by KthProg** [comment] 2015-05-08 00:27
Okay sounds good. I changed the name of the dataset, so that could be causing the issues. My first instinct would be to remove all data info from the controls.

**Comment by KthProg** [comment] 2015-05-08 22:31
I went through and removed all of the broken references, you should be able to run the app now. Once the UI changes are completed, I can tie each form into the database with stored procedures, then we can hook up the drop-downs themselves and call it a day.

**Comment by mgargano4** [comment] 2015-05-09 17:11
awesome thanks, i had a question about number 8, removing the large
calendar. what did you mean when you say display main screen when the
calendar button is clicked?

On Fri, May 8, 2015 at 6:31 PM, KthProg notifications@github.com wrote:

> I went through and removed all of the broken references. Once the UI
> changes are completed, I can tie each form into the database with stored
> procedures, then we can hook up the drop-downs themselves and call it a day.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ITCS2250/HorseFarm/issues/8#issuecomment-100386061.

## 

www.mgargano.com
LinkedIn Profile http://www.linkedin.com/pub/matthew-gargano/7a/306/712/

**Comment by KthProg** [comment] 2015-05-09 18:36
Oh yeah, I mean  switch to the main form. That way when they want to view the calendar, it can just display the calendar there (and filter by horse care only). Since we haven't put in the code to filter things yet, just programmatically check the horse care option.

**Comment by KthProg** [comment] 2015-05-09 21:44
Don't forget to close the issues when you're done with them. It looks like you finished a few of the different items.

**Comment by mgargano4** [comment] 2015-05-09 21:54
Sorry i still dont quite understand, maybe i just need a break. I got just
about everything else done if you wanna take a look whenever you get a
chance and let em know if i missed anything

On Sat, May 9, 2015 at 2:36 PM, KthProg notifications@github.com wrote:

> Oh yeah, I mean switch to the main screen. That way when they want to view
> the calendar, it can just display the calendar there (and filter by horse
> care only).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ITCS2250/HorseFarm/issues/8#issuecomment-100528412.

## 

www.mgargano.com
LinkedIn Profile http://www.linkedin.com/pub/matthew-gargano/7a/306/712/

**Comment by KthProg** [comment] 2015-05-09 21:58
On the GitHub page when you add a comment to an issue, there is a button to mark the issues as closed. The issues are obviously closed, but you haven't marked them as closed on GitHub. I could mark the issues as closed, but then it would look like I completed them, which I didn't.

**Closed as completed** 2015-05-09 23:35 UTC
Labels: user interface
